site_name: Nuvexa Docs
site_url: https://officialnuvexa.github.io/Nuvexa-Docs/
repo_url: https://github.com/OfficialNuvexa/Nuvexa-Docs
repo_name: OfficialNuvexa/Nuvexa-Docs
theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: blue
    accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - Welcome to Nuvexa: welcome.md
  - Executive Summary: executive-summary.md
  - Legal & Risk Disclaimer: legal-disclaimer.md
  - Contact & Partnerships: contact-partnerships.md
  - The Nuvexa Ecosystem:
      - Overview & Vision: overview-vision.md
      - Verticals Overview: verticals-overview.md
  - Nuvexa Technology Infrastructure:
      - Nuvexa Chain Overview: nuvexa-overview.md
      - Core Functionalities: core-functionalities.md
      - Technical Architecture: technical-architecture.md
      - Data Governance & Security: data-governance.md
      - Operational Workflow: operational-workflow.md
  - Social Links:
      - Twitter - @officialNuvexa: https://twitter.com/officialNuvexa
      - GitHub - Coming Soon: https://github.com/OfficialNuvexa

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji
  - pymdownx.tasklist
